[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5174
  targetPort = 5174

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Remove environment variable from toml file
# Environment variables should be set only in the Netlify UI
# and not referenced here to avoid string interpolation issues
